apiVersion: apps/v1
kind: Deployment
metadata:
  name: apdep
  namespace: app2
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: nginx-tp2
        image: nginx
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "10Mi"
            cpu: "250m"
        command: ["nginx"]
        args: ["-g daemon off;","-q"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mysite-configs
          mountPath: /etc/nginx/
      - name: hello-tp2
        image: emiup/hello
        imagePullPolicy: Always
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "10Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: registry-secret8
      volumes:
        - name: mysite-configs
          configMap:
            name: nginxconf