apiVersion: v1
kind: Service
metadata:
  name: hello-svc-lab
  namespace: apps-dev
  labels:
    app: hello-deploy
spec:
  type: NodePort
  selector:
    app: hello
    env: lab
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
