apiVersion: v1

kind: Pod
metadata:
  name: nginx-go
  namespace: apps-dev
spec:
  containers:
# NGINX
  - name: nginx
    image: greglebreton/nginx:nginx
    ports:
    - containerPort: 80
# GO APP
  - name: go    
    image: greglebreton/go_app
    ports:
    - containerPort: 8080

  imagePullSecrets:
  - name: docker-hub-cred
  dnsPolicy: ClusterFirst
  restartPolicy: Always