apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: hello-go
      namespace: deployment
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: somafairey/tp3.5:nginx
        ports: 
          - containerPort: 80 
      - name: go
        image: somafairey/tp3.5:hellogo
        ports:
          - containerPort: 8080 
      imagePullSecrets:
      - name: tp3secretkey-gmtc572dt8 

