apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-05-15T12:58:11Z"
  labels:
    app: nginx
  name: nginxexpose
  namespace: deployment
  resourceVersion: "215952"
  selfLink: /api/v1/namespaces/deployment/services/nginxexpose
  uid: 17de2cfc-7711-11e9-9660-080027692f6d
spec:
  clusterIP: 10.102.16.18
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32226
    port: 9584
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
